name: Cypress run testes
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - name: Cypress run
        run: npm test